### ISSUE TITLE
Missing @events/GetQuote.json

### ISSUE THREAD

**Issue by atacan** [swift-server/swift-openapi-lambda#6]
in the README we see

```bash
curl -v -X POST --header "Content-Type: application/json" --data @events/GetQuote.json  http://127.0.0.1:7000/invoke
```

but this repository doesn't not have events folder or json file.

**Comment by sebsto** [comment]
I added a sample JSON file for ease of use
https://github.com/swift-server/swift-openapi-lambda/commit/2b01689bcc2c3cc228e2c556f124345ddd6344bf
